#!/usr/bin/env bash
# Script to kill the 7-highlander process using SIGKILL (signal 9)

# Find the PID of 7-highlander process
pid=$(pgrep -f 7-highlander)

# If process is found, kill it with SIGKILL
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi

